version: '3.8'

services:
  nginx:
    image: alonecat/photo-stock-wp-nginx:latest
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  database:
    image: mysql:latest
    ports:
      - "3316:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${DB_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - backend-network

  wp-app:
    image: alonecat/photo-stock-wp-php:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - bedrock:/app:rw
      - acf_settings:/app/web/app/mu-plugins/awk-acfe:rw
    environment:
      WP_ENV: ${WP_ENV}
      WP_HOME: ${WP_HOME}
      WP_SITEURL: ${WP_SITEURL}
      DB_HOST: database:3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PREFIX: ${DB_PREFIX}
      AUTH_KEY: ${AUTH_KEY}
      SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
      LOGGED_IN_KEY: ${LOGGED_IN_KEY}
      NONCE_KEY: ${NONCE_KEY}
      AUTH_SALT: ${AUTH_SALT}
      SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
      LOGGED_IN_SALT: ${LOGGED_IN_SALT}
      NONCE_SALT: ${NONCE_SALT}
    ports:
      - "9000:9000"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  composer:
    image: composer
    deploy:
      replicas: 1
    volumes:
      - bedrock:/app
    entrypoint: ["composer", "install"]
    networks:
      - backend-network

  wp-cli:
    image: wordpress:cli
    deploy:
      replicas: 1
    user: "0"
    environment:
      WP_ENV: ${WP_ENV}
      WP_HOME: ${WP_HOME}
      WP_SITEURL: ${WP_SITEURL}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PREFIX: ${DB_PREFIX}
    entrypoint: ["bash", "-c", "wp core install --url=$WP_HOME --title=\"$WP_TITLE\" --admin_user=\"$WP_USER\" --admin_password=\"$WP_PASSWORD\" --admin_email=\"$WP_EMAIL\" --allow-root && wp language core install ru_RU --allow-root && wp language core activate ru_RU --allow-root && wp plugin install https://awkirin.ru/wp/plugins/acf-extended-pro.zip --allow-root && wp plugin install https://awkirin.ru/wp/plugins/advanced-custom-fields-pro.zip --allow-root && wp plugin activate --all --allow-root"]
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wp", "core", "is-installed"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

networks:
  backend-network:
    driver: overlay
    attachable: true

volumes:
  bedrock:
  database_data:
    external: true
  acf_settings:
    external: true
